version: '3.8'

services:
  # Servicio de la base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tiempos_en_vivo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Servicio de Laravel (backend)
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    restart: always
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: tiempos_en_vivo
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:x5pHJDRtNu/QhYhtRK03M2hv6XDAYVshxw58q5CITVQ=
      APP_URL: http://localhost:8000
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - app-network

  # Servicio de Next.js (frontend)
  nextjs:
    build:
      context: ./client-web
      dockerfile: Dockerfile
    container_name: nextjs
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/
    volumes:
      - ./client-web:/app
    ports:
      - "3000:3000"
    depends_on:
      - laravel
    networks:
      - app-network

# Definir volúmenes persistentes
volumes:
  mysql_data:

# Definir red de la aplicación
networks:
  app-network:
    driver: bridge
